window.MEDICOS_POR_UF = {
  AC: { id: 'med_ac', nome: 'ABEL FELIPE LEONARDO LIMA', crm: '3306/AC', uf: 'AC', cidade: 'Rio Branco', assinatura: '/assets/ABEL.png' },
  AL: { id: 'med_al', nome: 'BRUNO ALMEIDA VIANA DE OLIVEIRA', crm: '5270/AL', uf: 'AL', cidade: 'Maceió', assinatura: '/assets/BRUNO.png' },
  AM: { id: 'med_am', nome: 'CAIO CESAR VERAS PEREIRA', crm: '12906/AM', uf: 'AM', cidade: 'Manaus', assinatura: '/assets/CAIO.png' },
  AP: { id: 'med_ap', nome: 'DANILO AMÓRAS COLLARES GONSALVES', crm: '3060/AP', uf: 'AP', cidade: 'Macapá', assinatura: '/assets/DANILO.png' },
  BA: { id: 'med_ba', nome: 'EMANUELLY FREITAS DOS SANTOS LEMOS', crm: '33335/BA', uf: 'BA', cidade: 'Salvador', assinatura: '/assets/EMANUELLY.png' },
  CE: { id: 'med_ce', nome: 'FABIO AUGUSTO PORTELA OLIVEIRA', crm: '19317/CE', uf: 'CE', cidade: 'Fortaleza', assinatura: '/assets/FABIO.png' },
  DF: { id: 'med_df', nome: 'ADONAI PATRICK DE OLIVEIRA GABRIEL', crm: '31785/DF', uf: 'DF', cidade: 'Brasília', assinatura: '/assets/ADONAI.png' },
  ES: { id: 'med_es', nome: 'BRENDA GABRIEL DE MELO', crm: '21777/ES', uf: 'ES', cidade: 'Vitória', assinatura: '/assets/BRENDA.png' },
  GO: { id: 'med_go', nome: 'YAGO GABRIELL LOIOLA SPAGNOLY', crm: '33465/GO', uf: 'GO', cidade: 'Goiânia', assinatura: '/assets/YAGO.png' },
  MA: { id: 'med_ma', nome: 'GABRIEL COSTA SILVA', crm: '16062/MA', uf: 'MA', cidade: 'São Luís', assinatura: '/assets/GABRIEL.png' },
  MG: { id: 'med_mg', nome: 'HELIO ALVES FERREIRA JUNIOR', crm: '102566/MG', uf: 'MG', cidade: 'Belo Horizonte', assinatura: '/assets/HELIO.png' },
  MT: { id: 'med_mt', nome: 'ARI COUTINHO TIAGO SALDIBA NETO', crm: '14599/MT', uf: 'MT', cidade: 'Cuiabá', assinatura: '/assets/ARI.png' },
  MS: { id: 'med_ms', nome: 'JOSÉ ANDRÉ VITOR DA SILVA', crm: '12258/MS', uf: 'MS', cidade: 'Campo Grande', assinatura: '/assets/JOSE.png' },
  PA: { id: 'med_pa', nome: 'KAIO AUGUSTO DO NASCIMENTO FERREIRA', crm: '21635/PA', uf: 'PA', cidade: 'Belém', assinatura: '/assets/KAIO.png' },
  PB: { id: 'med_pb', nome: 'LEILA ALCINA CORREIA VAZ BUSTORFF CARTAXO', crm: '18217/PB', uf: 'PB', cidade: 'João Pessoa', assinatura: '/assets/LEILA.png' },
  PE: { id: 'med_pe', nome: 'LÍVIA MILLENA MORAIS SANTOS', crm: '40453/PE', uf: 'PE', cidade: 'Recife', assinatura: '/assets/LIVIA.png' },
  PI: { id: 'med_pi', nome: 'ELENILSON TORRES LAGES', crm: '4121/PI', uf: 'PI', cidade: 'Teresina', assinatura: '/assets/ELENILSON.png' },
  PR: { id: 'med_pr', nome: 'ALECSANDRO ZILIOTTO MACHADO', crm: '30194/PR', uf: 'PR', cidade: 'Curitiba', assinatura: '/assets/ALECSANDRO.png' },
  RJ: { id: 'med_rj', nome: 'VITOR PAULO DE FREITAS PEREZ', crm: '5283924-8/RJ', uf: 'RJ', cidade: 'Rio de Janeiro', assinatura: '/assets/VITOR.png' },
  RN: { id: 'med_rn', nome: 'MONICA URSULA FIGUEREDO SALES', crm: '9382/RN', uf: 'RN', cidade: 'Natal', assinatura: '/assets/MONICA.png' },
  RS: { id: 'med_rs', nome: 'BRUNA KAREN SUZIN', crm: '59948/RS', uf: 'RS', cidade: 'Porto Alegre', assinatura: '/assets/BRUNA.png' },
  RO: { id: 'med_ro', nome: 'RENATO BARBOSA FERREIRA', crm: '8942/RO', uf: 'RO', cidade: 'Porto Velho', assinatura: '/assets/RENATO.png' },
  RR: { id: 'med_rr', nome: 'SERGIO ANDRES GONZALEZ BRITO', crm: '483/RR', uf: 'RR', cidade: 'Boa Vista', assinatura: '/assets/SERGIO.png' },
  SC: { id: 'med_sc', nome: 'GETULIO ANTONIO SOARES JUNIOR', crm: '7909/SC', uf: 'SC', cidade: 'Florianópolis', assinatura: '/assets/GETULIO.png' },
  SP: { id: 'med_sp', nome: 'WANDERSON VINICIUS HENRIQUE', crm: '279687/SP', uf: 'SP', cidade: 'São Paulo', assinatura: '/assets/WANDERSON.png' },
  SE: { id: 'med_se', nome: 'DAVID ALEXANDER HIDALGO AGUILAR', crm: '9352/SE', uf: 'SE', cidade: 'Aracaju', assinatura: '/assets/DAVID.png' },
  TO: { id: 'med_to', nome: 'WENDELL VALE DE HOLANDA', crm: '6439/TO', uf: 'TO', cidade: 'Palmas', assinatura: '/assets/WENDELL.png' }
};